### PR TITLE
Ported to dotnet core 2.2

### PR DESCRIPTION
**Pull request by domiSchenk**

### CODE REVIEW

**Comment by alveflo** [comment]
Nice. Would it make more sense to port to netstandard though?

**Comment by mattiasnordqvist** [comment]
I think yes. System.Console seems to be netstandard compliant

**Comment by domiSchenk** [comment]
> Nice. Would it make more sense to port to netstandard though?

well i thought about the future of dotnet, it looks like there will be only .net 5

but i can convert it to dotnet Standard in the mean time.

**Comment by alveflo** [comment]
> > Nice. Would it make more sense to port to netstandard though?
> 
> well i thought about the future of dotnet, it looks like there will be only .net 5
> 
> but i can convert it to dotnet Standard in the mean time.

Oh ok, I see.... Yeah I think netstandard is the way to go at least for now 👍

**Comment by domiSchenk** [comment]
It is ready to merge. The library is now standard and the test console is core

**Comment by alveflo** [comment]
@domiSchenk nice work. You've got some conflicts that needs to be resolved before we can merge this though.

**Comment by domiSchenk** [comment]
so fixed the conflicts

**Comment by alveflo** [comment]
@domiSchenk merged and deployed to nuget. Thanks for your contribution 🎉

**Pull request merged**
